/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication17;

import java.awt.HeadlessException;
import java.sql.*;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Mahmut
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    int stokVarmi = 1;

    public NewJFrame() {
        initComponents();
        connectDatabase();
        showTed();
        showMusteri();
//        showbuyTable();
        showStokTable();
        showSiparis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        tedEkleButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tedTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        idpane = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        fnamepane = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        countrypane = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        productpane = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        quantitypane = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        datepane = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        lifepane = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        pricepane = new javax.swing.JTextPane();
        citypane = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane29 = new javax.swing.JScrollPane();
        yolMaliyeti = new javax.swing.JTextPane();
        uPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        uStokTable = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        olusturBilesen = new javax.swing.JTextField();
        olusturButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane28 = new javax.swing.JScrollPane();
        olusturMiktar = new javax.swing.JTextPane();
        mPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        mIdPane = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        mNamePane = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        mAdressPane = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        mProductPane = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        mQuanPane = new javax.swing.JTextPane();
        mEkleBtn = new javax.swing.JButton();
        adresGuncButton = new javax.swing.JButton();
        sPanel = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        siparisTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        karPane = new javax.swing.JTextPane();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        karPane2 = new javax.swing.JTextPane();

        jScrollPane5.setViewportView(jTextPane4);

        jScrollPane8.setViewportView(jTextPane7);

        jScrollPane14.setViewportView(jTextPane2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tedEkleButton.setText("Tedarikçi Ekle");
        tedEkleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tedEkleButtonActionPerformed(evt);
            }
        });

        tedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Firma Adi", "Ülke", "Şehir", "Madde", "Miktar", "Üretim Tarihi", "Raf Ömrü", "SatişFiyati"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tedTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tedTable);
        if (tedTable.getColumnModel().getColumnCount() > 0) {
            tedTable.getColumnModel().getColumn(4).setHeaderValue("Madde");
            tedTable.getColumnModel().getColumn(5).setHeaderValue("Miktar");
            tedTable.getColumnModel().getColumn(6).setHeaderValue("Üretim Tarihi");
            tedTable.getColumnModel().getColumn(7).setHeaderValue("Raf Ömrü");
            tedTable.getColumnModel().getColumn(8).setHeaderValue("SatişFiyati");
        }

        jLabel1.setText("ID");

        jLabel2.setText("Şirket Adı");

        jLabel3.setText("Ülke");

        jLabel4.setText("Şehir");

        jLabel5.setText("Madde");

        jLabel6.setText("Miktar");

        jLabel7.setText("Üretim Tarihi");

        jLabel8.setText("Raf Ömrü");

        jLabel9.setText("Satış Fiyatı");

        jScrollPane1.setViewportView(idpane);

        jScrollPane4.setViewportView(fnamepane);

        jScrollPane6.setViewportView(countrypane);

        jScrollPane9.setViewportView(productpane);

        jScrollPane10.setViewportView(quantitypane);

        jScrollPane11.setViewportView(datepane);

        jScrollPane12.setViewportView(lifepane);

        jScrollPane13.setViewportView(pricepane);

        citypane.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ankara", "Eskisehir", "Gaziantep", "İstanbul", "Londra", "Berlin", "Saraybosna" }));

        jButton5.setText("Tabloyu Güncelle");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel26.setText("Kargo Maliyeti:");

        yolMaliyeti.setEditable(false);
        jScrollPane29.setViewportView(yolMaliyeti);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5)))
                .addGap(63, 63, 63)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(citypane, 0, 0, Short.MAX_VALUE))
                .addGap(104, 104, 104)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton5)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(81, 81, 81)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(tedEkleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addComponent(jButton5))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(tedEkleButton))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(citypane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel8))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jLabel26))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout tPanelLayout = new javax.swing.GroupLayout(tPanel);
        tPanel.setLayout(tPanelLayout);
        tPanelLayout.setHorizontalGroup(
            tPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tPanelLayout.setVerticalGroup(
            tPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tedarikçi", tPanel);

        jLabel20.setFont(new java.awt.Font("Sylfaen", 1, 20)); // NOI18N
        jLabel20.setText("Üretici Stok Durumu");

        uStokTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bileşiğin Adi", "Miktari"
            }
        ));
        jScrollPane25.setViewportView(uStokTable);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 0, 0));
        jLabel22.setText("Yeni Bileşen Oluştur");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 153));
        jLabel23.setText("Örnek Oluşturma Şekli:      C.1-O.2 / H.2-O.1 / H.1-Cl.1");

        olusturBilesen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olusturBilesenActionPerformed(evt);
            }
        });

        olusturButton.setText("Oluştur");
        olusturButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olusturButtonActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel25.setText("Mikatarini Giriniz: ");

        jScrollPane28.setViewportView(olusturMiktar);

        javax.swing.GroupLayout uPanelLayout = new javax.swing.GroupLayout(uPanel);
        uPanel.setLayout(uPanelLayout);
        uPanelLayout.setHorizontalGroup(
            uPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(uPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                    .addGroup(uPanelLayout.createSequentialGroup()
                        .addGroup(uPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(uPanelLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(48, 48, 48)
                                .addComponent(jScrollPane28))
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(olusturBilesen))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(olusturButton)
                .addGap(107, 107, 107))
        );
        uPanelLayout.setVerticalGroup(
            uPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(uPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(uPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(28, 28, 28)
                        .addComponent(olusturBilesen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(olusturButton)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25))
                    .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Üretici/Satici", uPanel);

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Müsteri Adi", "Adres", "Talep Edilen Ürün", "Adet"
            }
        ));
        customerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(customerTable);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel10.setText("Sisteme Kayıtlı Olan Müsteriler");

        jLabel11.setText("ID");

        jLabel12.setText("Müsteri Adı");

        jLabel13.setText("Adres");

        jLabel14.setText("Talep Edilen Ürün");

        jLabel15.setText("Talep Edilen Miktar");

        jScrollPane15.setViewportView(mIdPane);

        jScrollPane7.setViewportView(mNamePane);

        jScrollPane16.setViewportView(mAdressPane);

        jScrollPane17.setViewportView(mProductPane);

        jScrollPane18.setViewportView(mQuanPane);

        mEkleBtn.setText("Müşteri Ekle");
        mEkleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEkleBtnActionPerformed(evt);
            }
        });

        adresGuncButton.setText("Müşteri Adres Güncelle");
        adresGuncButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresGuncButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mPanelLayout = new javax.swing.GroupLayout(mPanel);
        mPanel.setLayout(mPanelLayout);
        mPanelLayout.setHorizontalGroup(
            mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(mPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(mPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jScrollPane16)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane17)
                    .addComponent(jScrollPane18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mEkleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adresGuncButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125))
        );
        mPanelLayout.setVerticalGroup(
            mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mPanelLayout.createSequentialGroup()
                                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(mPanelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86)
                                        .addComponent(jLabel11))
                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(mPanelLayout.createSequentialGroup()
                                        .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(mPanelLayout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel13))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(mEkleBtn)
                                                .addGap(17, 17, 17))))
                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mPanelLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel14))
                                    .addGroup(mPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(adresGuncButton))))
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15)))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Müşteri", mPanel);

        siparisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Müsteri Adi", "Sehir Merkezi", "Talep Edilen Ürün", "Adet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        siparisTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siparisTableMouseClicked(evt);
            }
        });
        jScrollPane19.setViewportView(siparisTable);

        jLabel16.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel16.setText("Seçili olan siparişten elde edilen kar: ");

        karPane.setEditable(false);
        jScrollPane20.setViewportView(karPane);

        jLabel18.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel18.setText("Kar Oranı (%): ");

        karPane2.setEditable(false);
        jScrollPane21.setViewportView(karPane2);

        javax.swing.GroupLayout sPanelLayout = new javax.swing.GroupLayout(sPanel);
        sPanel.setLayout(sPanelLayout);
        sPanelLayout.setHorizontalGroup(
            sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addGroup(sPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(sPanelLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(133, 133, 133)
                                .addComponent(jScrollPane21))
                            .addGroup(sPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        sPanelLayout.setVerticalGroup(
            sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(340, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Siparişler", sPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siparisTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siparisTableMouseClicked
        int rowCount = siparisTable.getSelectedRow();
        TableModel model = siparisTable.getModel();
        int toplamMaliyet = 0, satisFiyati = 0; 
        int mustid = Integer.parseInt(model.getValueAt(rowCount, 0).toString());
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey",
                "root", "");

            String q = "Select toplamMaliyet, satisFiyati FROM siparis Where siparis.musteriID = "+ mustid;
            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery(q);
            while (rs.next()) {
                toplamMaliyet = rs.getInt(1);
                satisFiyati = rs.getInt(2);
            }
            statement.close();
            rs.close();
            String temp;
            double kar = (double)(((double)satisFiyati - (double)toplamMaliyet) / toplamMaliyet) * 100 ;
            NumberFormat nf =NumberFormat.getInstance(); // nf adında bir NumberFormat tanımladık. Siz başka birşey diyebilirsiniz.

        nf.setMaximumFractionDigits(2);      // Burada virgülden sonra maksimum 2 karakter olacağı belirtiliyor.

        nf.setMinimumFractionDigits(2);      // Burada virgülden sonra minimum 2 karakter olacağı belirtiliyor.

        String s= nf.format(kar);          // nf.format(x)  string bir değer döndüdür sonuc s değişkenine atanır. x ise virgüllü sayımızdır.   
            temp = ""+(satisFiyati - toplamMaliyet);
            karPane.setText(temp); 
            temp = ""+ kar;
            karPane2.setText(s);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_siparisTableMouseClicked

    private void adresGuncButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresGuncButtonActionPerformed
        // TODO add your handling code here:
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey", "root", "");
            int sRow = customerTable.getSelectedRow();
            String value = (customerTable.getModel().getValueAt(sRow, 0).toString());
            String q = "Update musteri set musteri.adres = ? where musteri.ID =" + value;

            String yeniAdres = mAdressPane.getText();
            System.out.println(value + yeniAdres);
            PreparedStatement ps = con.prepareStatement(q);
            ps.setString(1, yeniAdres);
            ps.executeUpdate();
            DefaultTableModel tableModel = (DefaultTableModel) customerTable.getModel();
            tableModel.setRowCount(0);
            showMusteri();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_adresGuncButtonActionPerformed

    private void mEkleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEkleBtnActionPerformed
        // TODO add your handling code here:
        String adres = mAdressPane.getText();
        int ym = 0;
        boolean yd = false;
        double km = 0;
        int im = Integer.parseInt(mQuanPane.getText());

        if (adres.contains("istanbul")) {
            ym = 111;
            yd = false;
            km = 111 * 0.5;
        } else if (adres.contains("ankara")) {
            ym = 342;
            yd = false;
            km = 342 * 0.5;
        } else if (adres.contains("eskisehir")) {
            ym = 214;
            yd = false;
            km = 214 * 0.5;
        } else if (adres.contains("gaziantep")) {
            ym = 1000;
            yd = false;
            km = 1000 * 0.5;
        } else if (adres.contains("londra")) {
            ym = 2582;
            yd = true;
            km = 2582;
        } else if (adres.contains("berlin")) {
            ym = 1809;
            yd = true;
            km = 1809;
        } else if (adres.contains("saraybosna")) {
            ym = 1008;
            yd = true;
            km = 1008;
        }
        int toplamM = im + (int) km;
        int sfiyati = toplamM * 6 / 5;
        int sonSiparis = 0;
        int urunid = 0, urunStok = 0;
        System.out.println(km + "->km" + im + "-" + toplamM);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey",
                "root", "");

            String query = "SELECT `ID` FROM `siparis` WHERE 1";
            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery(query);
            while (rs.next()) {
                sonSiparis = rs.getInt(1);
            }
            System.out.println(sonSiparis);
            statement.close();
            rs.close();

            query = "select urunler.ID from urunler where urunler.urunAd = " + "'" + mProductPane.getText() + "'";
            statement = con.createStatement();
            rs = statement.executeQuery(query);
            while (rs.next()) {
                urunid = rs.getInt(1);
            }

            statement.close();
            rs.close();

            query = "select urunler.stok from urunler where urunler.ID = " + urunid;
            statement = con.createStatement();
            rs = statement.executeQuery(query);
            while (rs.next()) {
                urunStok = rs.getInt(1);
            }

            statement.close();
            rs.close();

            int sAdet = Integer.parseInt(mQuanPane.getText());
            if (urunStok >= sAdet) {

                String q = "INSERT INTO `musteri`(`ID`, `musteriAdi`, `adres`) VALUES (?, ?, ?)";
                PreparedStatement pst = con.prepareStatement(q);

                int tempInt = Integer.parseInt(mIdPane.getText());
                pst.setInt(1, tempInt);
                pst.setString(2, mNamePane.getText());
                pst.setString(3, mAdressPane.getText());
                pst.executeUpdate();
                pst.close();
                q = "INSERT INTO `siparis`(`ID`, `urunID`, `musteriID`, `urunAdet`,"
                + " `isciMaliyet`, `toplamMaliyet`, `satisFiyati`)"
                + " VALUES (?, ?, ?, ?, ?, ?, ?)";
                pst = con.prepareStatement(q);
                sonSiparis += 1;
                pst.setInt(1, sonSiparis);
                pst.setInt(2, urunid);
                pst.setInt(3, tempInt);
                tempInt = Integer.parseInt(mQuanPane.getText());
                pst.setInt(4, tempInt);
                pst.setInt(5, im);
                pst.setInt(6, toplamM);
                pst.setInt(7, sfiyati);
                pst.executeUpdate();

                q = "update urunler set urunler.stok = ? where urunler.ID = " + urunid;
                pst = con.prepareStatement(q);
                int stokSon = urunStok - tempInt;
                pst.setInt(1, stokSon);
                pst.executeUpdate();

                tablolariGuncelle();
            } else {
                String q = "INSERT INTO `musteri`(`ID`, `musteriAdi`, `adres`) VALUES (?, ?, ?)";
                PreparedStatement pst = con.prepareStatement(q);

                int tempInt = Integer.parseInt(mIdPane.getText());
                pst.setInt(1, tempInt);
                pst.setString(2, mNamePane.getText());
                pst.setString(3, mAdressPane.getText());
                pst.executeUpdate();
                pst.close();
                q = "INSERT INTO `siparis`(`ID`, `urunID`, `musteriID`, `urunAdet`,"
                + " `isciMaliyet`, `toplamMaliyet`, `satisFiyati`)"
                + " VALUES (?, ?, ?, ?, ?, ?, ?)";
                pst = con.prepareStatement(q);
                sonSiparis += 1;
                pst.setInt(1, sonSiparis);
                pst.setInt(2, urunid);
                pst.setInt(3, tempInt);
                tempInt = Integer.parseInt(mQuanPane.getText());
                pst.setInt(4, tempInt);
                pst.setInt(5, im);
                pst.setInt(6, toplamM);
                pst.setInt(7, sfiyati);
                pst.executeUpdate();

                tedarikcidenHammaddeAl(mProductPane.getText(), Integer.parseInt(mQuanPane.getText()));

                pst = con.prepareStatement(query);
                query = "update urunler set urunler.stok = ? where urunAd = "+"'"+mProductPane.getText()+"'";
                pst = con.prepareStatement(query);
                int stokSon = 0;
                pst.setInt(1, stokSon);
                pst.executeUpdate();

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tablolariGuncelle();
    }//GEN-LAST:event_mEkleBtnActionPerformed

    private void customerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerTableMouseClicked
        // TODO add your handling code here:
        int rowCount = customerTable.getSelectedRow();
        TableModel model = customerTable.getModel();

        mIdPane.setText(model.getValueAt(rowCount, 0).toString());
        mNamePane.setText(model.getValueAt(rowCount, 1).toString());
        mAdressPane.setText(model.getValueAt(rowCount, 2).toString());
        mProductPane.setText(model.getValueAt(rowCount, 3).toString());
        mQuanPane.setText(model.getValueAt(rowCount, 4).toString());
    }//GEN-LAST:event_customerTableMouseClicked

    private void olusturBilesenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olusturBilesenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_olusturBilesenActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) tedTable.getModel();
        tableModel.setRowCount(0);
        showTed();
        stokKontrol();
        System.out.println("Tablo güncellendi.");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tedTableMouseClicked
        // TODO add your handling code here:
        int rowCount = tedTable.getSelectedRow();
        TableModel model = tedTable.getModel();
        idpane.setText(model.getValueAt(rowCount, 0).toString());
        fnamepane.setText(model.getValueAt(rowCount, 1).toString());
        countrypane.setText(model.getValueAt(rowCount, 2).toString());
        String city = model.getValueAt(rowCount, 3).toString();

        switch (city) {
            case "Ankara":
            citypane.setSelectedIndex(0);
            break;
            case "Eskisehir":
            citypane.setSelectedIndex(1);
            break;
            case "Gaziantep":
            citypane.setSelectedIndex(2);
            break;
            case "Istanbul":
            citypane.setSelectedIndex(3);
            break;
            case "Londra":
            citypane.setSelectedIndex(4);
            break;
            case "Berlin":
            citypane.setSelectedIndex(5);
            break;
            case "Saraybosna":
            citypane.setSelectedIndex(6);
            break;

        }
        productpane.setText(model.getValueAt(rowCount, 4).toString());
        quantitypane.setText(model.getValueAt(rowCount, 5).toString());
        datepane.setText(model.getValueAt(rowCount, 6).toString());
        lifepane.setText(model.getValueAt(rowCount, 7).toString());
        pricepane.setText(model.getValueAt(rowCount, 8).toString());
        switch (city) {
            case "Ankara":
            yolMaliyeti.setText("171");
            break;
            case "Eskisehir":
            yolMaliyeti.setText("107");
            break;
            case "Gaziantep":
            yolMaliyeti.setText("500");
            break;
            case "Istanbul":
            yolMaliyeti.setText("55");
            break;
            case "Londra":
            yolMaliyeti.setText("2582");
            break;
            case "Berlin":
            yolMaliyeti.setText("1809");
            break;
            case "Saraybosna":
            yolMaliyeti.setText("1008");
            break;

        }
        
    }//GEN-LAST:event_tedTableMouseClicked

    private void tedEkleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tedEkleButtonActionPerformed
        // TODO add your handling code here:
        int sonTedHammadde = 0;
        int uretilenHammadde = 0;

        String uhm = productpane.getText();
        if (uhm.equalsIgnoreCase("H")) {
            uretilenHammadde = 1;
        } else if (uhm.equalsIgnoreCase("N")) {
            uretilenHammadde = 2;
        } else if (uhm.equalsIgnoreCase("C")) {
            uretilenHammadde = 3;
        } else if (uhm.equalsIgnoreCase("O")) {
            uretilenHammadde = 4;
        } else if (uhm.equalsIgnoreCase("S")) {
            uretilenHammadde = 5;
        } else if (uhm.equalsIgnoreCase("Cl")) {
            uretilenHammadde = 6;
        }

        String adres = citypane.getSelectedItem().toString();

        if (adres.contains("istanbul")) {

            yolm = 111 * 0.5;
        } else if (adres.contains("ankara")) {

            yolm = 342 * 0.5;
        } else if (adres.contains("eskisehir")) {

            yolm = 214 * 0.5;
        } else if (adres.contains("gaziantep")) {

            yolm = 1000 * 0.5;
        } else if (adres.contains("londra")) {

            yolm = 2582;
        } else if (adres.contains("berlin")) {

            yolm = 1809;
        } else if (adres.contains("saraybosna")) {
            yolm = 1008;
        }

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey",
                "root", "");

            String q = "Select tedhammadde.ID FROM tedhammadde";
            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery(q);
            while (rs.next()) {
                sonTedHammadde = rs.getInt(1);
            }

            System.out.println(sonTedHammadde);
            statement.close();
            rs.close();
            
            int tedarikcid = 0;
            q = "Select ID from tedarikci";
            statement = con.createStatement();
            rs = statement.executeQuery(q);
            while (rs.next()) {
                tedarikcid = rs.getInt(1);
            }
            statement.close();
            rs.close();

            String insertquery = "INSERT INTO `tedarikci`(`ID`, `firmaAdi`, `ulke`, `sehir`)values(?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(insertquery);
            int tempInt = Integer.parseInt(idpane.getText());
            int uretenfirmaID = tempInt;
            pst.setInt(1, uretenfirmaID);
            pst.setString(2, fnamepane.getText());
            pst.setString(3, countrypane.getText());
            pst.setString(4, citypane.getSelectedItem().toString());
            pst.executeUpdate();

            sonTedHammadde += 1;
            insertquery = "INSERT INTO `tedhammadde`(`ID`, `uretenFirmaID`, `hammaddeID`, `stok`, `fiyat`, `uretimTarihi`, `rafomru`)"
            + " VALUES ( ?, ?, ?, ?, ?, ?, ?)";
            pst = con.prepareStatement(insertquery);

            pst.setInt(1, sonTedHammadde);
            pst.setInt(2, uretenfirmaID);
            pst.setInt(3, uretilenHammadde);
            tempInt = Integer.parseInt(quantitypane.getText());
            pst.setInt(4, tempInt);
            iscim = tempInt;
            tempInt = Integer.parseInt(pricepane.getText());
            pst.setInt(5, tempInt);
            pst.setString(6, datepane.getText());
            tempInt = Integer.parseInt(lifepane.getText());
            pst.setInt(7, tempInt);

            pst.executeUpdate();
            DefaultTableModel tableModel = (DefaultTableModel) tedTable.getModel();
            tableModel.setRowCount(0);
            showTed();
            JOptionPane.showMessageDialog(null, "Inserted successfully");

            idpane.setText("");
            fnamepane.setText("");
            countrypane.setText("");
            citypane.setSelectedIndex(0);
            productpane.setText("");
            quantitypane.setText("");
            datepane.setText("");
            lifepane.setText("");
            pricepane.setText("");

        } catch (SQLIntegrityConstraintViolationException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tedEkleButtonActionPerformed

    private void olusturButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olusturButtonActionPerformed
        String bilesen = olusturBilesen.getText();
        String sadet = olusturMiktar.getText();
        System.out.println(bilesen + " - "+ sadet);
        int adet = Integer.parseInt(sadet);
        tedarikcidenHammaddeAl(bilesen, adet);
        tablolariGuncelle();
    }//GEN-LAST:event_olusturButtonActionPerformed
    double yolm = 0;
    int iscim = 0;
    //Splitter: String i - lara göre array a böler
    public static String[] splitter(String str) {
        String data[] = str.split("-");
        return data;
    }

    //Splitter: String i bilesenlere göre array a böler
    public static String[] splitter1(String str) {
        String data[] = str.split("\\.");
        return data;
    }

    private void tedarikcidenHammaddeAl(String bilesen, int sAdet) {

        System.out.println("Tedarikciden hammadde satın alınıyor");

        int sAlinacakhadeti, sAlinacakhadeti1, sAlinacakhadeti3;

        String[] bilesenArray = splitter(bilesen);
        if (bilesenArray.length == 2) {

            String[] ham = splitter1(bilesenArray[0]);
            System.out.println("bilesenArray[0]  --> " + bilesenArray[0]);
            String ham1 = ham[0];
            int adet = Integer.parseInt(ham[1]);

            String[] h2 = splitter1(bilesenArray[1]);
            String ham2 = h2[0];
            int adet2 = Integer.parseInt(h2[1]);

            sAlinacakhadeti = adet * sAdet;
            sAlinacakhadeti1 = adet2 * sAdet;

            String uhm = ham1;
            int uretilenHammadde = 0;
            if (uhm.equalsIgnoreCase("H")) {
                uretilenHammadde = 1;
            } else if (uhm.equalsIgnoreCase("N")) {
                uretilenHammadde = 2;
            } else if (uhm.equalsIgnoreCase("C")) {
                uretilenHammadde = 3;
            } else if (uhm.equalsIgnoreCase("O")) {
                uretilenHammadde = 4;
            } else if (uhm.equalsIgnoreCase("S")) {
                uretilenHammadde = 5;
            } else if (uhm.equalsIgnoreCase("Cl")) {
                uretilenHammadde = 6;
            }

            String uhm2 = ham2;
            int uretilenHammadde2 = 0;
            if (uhm2.equalsIgnoreCase("H")) {
                uretilenHammadde2 = 1;
            } else if (uhm2.equalsIgnoreCase("N")) {
                uretilenHammadde2 = 2;
            } else if (uhm2.equalsIgnoreCase("C")) {
                uretilenHammadde2 = 3;
            } else if (uhm2.equalsIgnoreCase("O")) {
                uretilenHammadde2 = 4;
            } else if (uhm2.equalsIgnoreCase("S")) {
                uretilenHammadde2 = 5;
            } else if (uhm2.equalsIgnoreCase("Cl")) {
                uretilenHammadde2 = 6;
            }
            int urunStok = 0;
            try {

                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey", "root", "");
                String uretilenh = "" + uretilenHammadde;

                String query = "SELECT tedhammadde.uretenFirmaID FROM tedhammadde WHERE tedhammadde.hammaddeID = "+uretilenHammadde +" ORDER BY tedhammadde.fiyat";
                Statement s = con.createStatement();
                ResultSet rs = s.executeQuery(query);
                int firmaid = 0;
                while (rs.next()) {
                    firmaid = rs.getInt(1);
                }
                s.close();
                rs.close();

                query = "select tedhammadde.stok from tedhammadde where uretenFirmaID = " + firmaid + " AND tedhammadde.hammaddeID = " + uretilenHammadde;
                s = con.createStatement();
                rs = s.executeQuery(query);
                while (rs.next()) {
                    urunStok = rs.getInt(1);
                }

                s.close();
                rs.close();

                query = "update tedhammadde set tedhammadde.stok = ? where uretenFirmaID = " + firmaid + " AND hammaddeID = " + uretilenHammadde;
                PreparedStatement pst = con.prepareStatement(query);
                int stokSon = urunStok - sAlinacakhadeti;
                pst.setInt(1, stokSon);
                pst.executeUpdate();

                //urun iki
                query = "SELECT `uretenFirmaID` FROM tedhammadde WHERE hammaddeID =" + uretilenHammadde2 + " ORDER BY fiyat DESC";
                s = con.createStatement();
                rs = s.executeQuery(query);
                firmaid = 0;
                while (rs.next()) {
                    firmaid = rs.getInt(1);
                }
                s.close();
                rs.close();

                query = "select tedhammadde.stok from tedhammadde where uretenFirmaID = " + firmaid + " AND hammaddeID = " + uretilenHammadde2;
                s = con.createStatement();
                rs = s.executeQuery(query);
                while (rs.next()) {
                    urunStok = rs.getInt(1);
                }

                s.close();
                rs.close();

                query = "update tedhammadde set tedhammadde.stok = ? where uretenFirmaID = " + firmaid + " AND hammaddeID = " + uretilenHammadde2;
                pst = con.prepareStatement(query);
                stokSon = urunStok - sAlinacakhadeti1;
                pst.setInt(1, stokSon);
                pst.executeUpdate();

                bilesenOlustur(bilesen, sAdet);

            } catch (Exception e) {
                e.printStackTrace();
            }

        } else if (bilesenArray.length == 3) {
            String[] ham = splitter1(bilesenArray[0]);
            System.out.println("bilesenArray[0]  --> " + bilesenArray[0]);
            String ham1 = ham[0];
            int adet = Integer.parseInt(ham[1]);

            String[] h2 = splitter1(bilesenArray[1]);
            String ham2 = h2[0];
            int adet2 = Integer.parseInt(h2[1]);
            
            String[] h3 = splitter1(bilesenArray[2]);
            String ham3 = h3[0];
            int adet3 = Integer.parseInt(h3[1]);
            
            sAlinacakhadeti = adet * sAdet;
            sAlinacakhadeti1 = adet2 * sAdet;
            sAlinacakhadeti3 = adet3 * sAdet;

            String uhm = ham1;
            int uretilenHammadde = 0;
            if (uhm.equalsIgnoreCase("H")) {
                uretilenHammadde = 1;
            } else if (uhm.equalsIgnoreCase("N")) {
                uretilenHammadde = 2;
            } else if (uhm.equalsIgnoreCase("C")) {
                uretilenHammadde = 3;
            } else if (uhm.equalsIgnoreCase("O")) {
                uretilenHammadde = 4;
            } else if (uhm.equalsIgnoreCase("S")) {
                uretilenHammadde = 5;
            } else if (uhm.equalsIgnoreCase("Cl")) {
                uretilenHammadde = 6;
            }

            String uhm2 = ham2;
            int uretilenHammadde2 = 0;
            if (uhm2.equalsIgnoreCase("H")) {
                uretilenHammadde2 = 1;
            } else if (uhm2.equalsIgnoreCase("N")) {
                uretilenHammadde2 = 2;
            } else if (uhm2.equalsIgnoreCase("C")) {
                uretilenHammadde2 = 3;
            } else if (uhm2.equalsIgnoreCase("O")) {
                uretilenHammadde2 = 4;
            } else if (uhm2.equalsIgnoreCase("S")) {
                uretilenHammadde2 = 5;
            } else if (uhm2.equalsIgnoreCase("Cl")) {
                uretilenHammadde2 = 6;
            }
            
            String uhm3 = ham3;
            int uretilenHammadde3 = 0;
            if (uhm3.equalsIgnoreCase("H")) {
                uretilenHammadde3 = 1;
            } else if (uhm3.equalsIgnoreCase("N")) {
                uretilenHammadde3 = 2;
            } else if (uhm3.equalsIgnoreCase("C")) {
                uretilenHammadde3 = 3;
            } else if (uhm3.equalsIgnoreCase("O")) {
                uretilenHammadde3 = 4;
            } else if (uhm3.equalsIgnoreCase("S")) {
                uretilenHammadde3 = 5;
            } else if (uhm3.equalsIgnoreCase("Cl")) {
                uretilenHammadde3 = 6;
            }
            
            int urunStok = 0;
            try {

                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey", "root", "");
                String uretilenh = "" + uretilenHammadde;

                String query = "SELECT tedhammadde.uretenFirmaID FROM tedhammadde WHERE tedhammadde.hammaddeID = "+uretilenHammadde +" ORDER BY tedhammadde.fiyat";
                Statement s = con.createStatement();
                ResultSet rs = s.executeQuery(query);
                int firmaid = 0;
                while (rs.next()) {
                    firmaid = rs.getInt(1);
                }
                s.close();
                rs.close();

                query = "select tedhammadde.stok from tedhammadde where uretenFirmaID = " + firmaid + " AND tedhammadde.hammaddeID = " + uretilenHammadde;
                s = con.createStatement();
                rs = s.executeQuery(query);
                while (rs.next()) {
                    urunStok = rs.getInt(1);
                }

                s.close();
                rs.close();

                query = "update tedhammadde set tedhammadde.stok = ? where uretenFirmaID = " + firmaid + " AND hammaddeID = " + uretilenHammadde;
                PreparedStatement pst = con.prepareStatement(query);
                int stokSon = urunStok - sAlinacakhadeti;
                pst.setInt(1, stokSon);
                pst.executeUpdate();

                //urun iki
                query = "SELECT `uretenFirmaID` FROM tedhammadde WHERE hammaddeID =" + uretilenHammadde2 + " ORDER BY fiyat DESC";
                s = con.createStatement();
                rs = s.executeQuery(query);
                firmaid = 0;
                while (rs.next()) {
                    firmaid = rs.getInt(1);
                }
                s.close();
                rs.close();

                query = "select tedhammadde.stok from tedhammadde where uretenFirmaID = " + firmaid + " AND hammaddeID = " + uretilenHammadde2;
                s = con.createStatement();
                rs = s.executeQuery(query);
                while (rs.next()) {
                    urunStok = rs.getInt(1);
                }

                s.close();
                rs.close();

                query = "update tedhammadde set tedhammadde.stok = ? where uretenFirmaID = " + firmaid + " AND hammaddeID = " + uretilenHammadde2;
                pst = con.prepareStatement(query);
                stokSon = urunStok - sAlinacakhadeti1;
                pst.setInt(1, stokSon);
                pst.executeUpdate();

                //urun üç
                query = "SELECT `uretenFirmaID` FROM tedhammadde WHERE hammaddeID =" + uretilenHammadde3 + " ORDER BY fiyat DESC";
                s = con.createStatement();
                rs = s.executeQuery(query);
                firmaid = 0;
                while (rs.next()) {
                    firmaid = rs.getInt(1);
                }
                s.close();
                rs.close();

                query = "select tedhammadde.stok from tedhammadde where uretenFirmaID = " + firmaid + " AND hammaddeID = " + uretilenHammadde3;
                s = con.createStatement();
                rs = s.executeQuery(query);
                while (rs.next()) {
                    urunStok = rs.getInt(1);
                }

                s.close();
                rs.close();

                query = "update tedhammadde set tedhammadde.stok = ? where uretenFirmaID = " + firmaid + " AND hammaddeID = " + uretilenHammadde3;
                pst = con.prepareStatement(query);
                stokSon = urunStok - sAlinacakhadeti1;
                pst.setInt(1, stokSon);
                pst.executeUpdate();

                
                bilesenOlustur(bilesen, sAdet);

            } catch (Exception e) {
                e.printStackTrace();
            }

        }

    }

    public void bilesenOlustur(String bilesen, int sAdet) {
        System.out.println("bileşen oluşturuluyor");
        
        System.out.println(bilesen);
        
        int bilid = 0, urunid = 0;
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey",
                    "root", "");

            String query = "SELECT `ID` FROM `urunler` WHERE urunAd = " +"'"+bilesen+"'";
            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery(query);
            while (rs.next()) {
                bilid = rs.getInt(1);
            }

            statement.close();
            rs.close();

            if (bilid == 0) {

                query = "SELECT `ID` FROM `urunler` WHERE 1";
                statement = con.createStatement();
                rs = statement.executeQuery(query);
                while (rs.next()) {
                    urunid = rs.getInt(1);
                }

                statement.close();
                rs.close();

                query = "INSERT INTO `urunler`(`ID`, `ureticiID`, `urunAd`, `stok`, `uretimTarihi`, `rafOmru`) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement pst = con.prepareStatement(query);
                urunid += 1;
                pst.setInt(1, urunid);
                pst.setInt(2, 1);
                pst.setString(3, bilesen);
                pst.setInt(4, sAdet);
                pst.setString(5, "22052019");
                pst.setInt(6, 5);

                pst.executeUpdate();
                pst.close();
            } else {
                int urunStok = 0;
                query = "select urunler.stok from urunler where urunler.ID = " + bilid;
                statement = con.createStatement();
                rs = statement.executeQuery(query);
                while (rs.next()) {
                    urunStok = rs.getInt(1);
                }

                statement.close();
                rs.close();

                PreparedStatement pst = con.prepareStatement(query);
                query = "update urunler set urunler.stok = ? where urunler.ID = " + bilid;
                pst = con.prepareStatement(query);
                int stokSon = urunStok + sAdet;
                pst.setInt(1, stokSon);
                pst.executeUpdate();
                
                
                
                System.out.println("Bileşen oluşturuldu");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        tablolariGuncelle();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);

            }
        });
    }
    public void tablolariGuncelle(){
        
        DefaultTableModel tableModel = null;
        tableModel = (DefaultTableModel) tedTable.getModel();
        tableModel.setRowCount(0);
        tableModel = (DefaultTableModel) uStokTable.getModel();
        tableModel.setRowCount(0);
        tableModel = (DefaultTableModel) siparisTable.getModel();
        tableModel.setRowCount(0);
        tableModel = (DefaultTableModel) customerTable.getModel();
        tableModel.setRowCount(0);
        
        stokKontrol();
        
        showTed();
        showMusteri();
        showStokTable();
        showSiparis();
    }
    public void stokKontrol() {
        String query = "DELETE FROM `tedhammadde` WHERE stok <= 0";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey",
                    "root", "");
            PreparedStatement pst = con.prepareStatement(query);
            pst.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public ArrayList<Ted> tedList() {
        ArrayList<Ted> tedList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey",
                    "root", "");
            String query1 = "SELECT tedarikci.ID, tedarikci.firmaAdi, tedarikci.ulke, tedarikci.sehir, hammadde.isim,"
                    + " tedhammadde.stok, tedhammadde.uretimTarihi, tedhammadde.rafomru, tedhammadde.fiyat FROM tedhammadde "
                    + "INNER JOIN hammadde ON tedhammadde.hammaddeID = hammadde.ID INNER JOIN tedarikci ON tedhammadde.uretenFirmaID = tedarikci.ID"
                    + " Where tedhammadde.stok > 0  Order By hammadde.isim";
            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery(query1);
            Ted ted;
            //"ID  -CName  -Contry  -Product  -Quantity  -PDate  -ShelfLife  -SaleP"
            while (rs.next()) {
                ted = new Ted(rs.getInt(1), rs.getString(2), rs.getString(3),
                        rs.getString(4), rs.getString(5), rs.getInt(6),
                        rs.getString(7), rs.getInt(8), rs.getInt(9));
                tedList.add(ted);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return tedList;
    }

    public ArrayList<Musteri> musteriList() {
        ArrayList<Musteri> mList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey",
                    "root", "");
            String query1 = "SELECT musteri.ID, musteri.musteriAdi, musteri.adres, urunler.urunAd,siparis.urunAdet FROM siparis, musteri, urunler "
                    + "WHERE siparis.musteriID = musteri.ID AND siparis.urunID = urunler.ID"
                    + " Order By musteri.ID";
            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery(query1);
            Musteri med;
            while (rs.next()) {
                med = new Musteri(rs.getInt(1), rs.getString(2), rs.getString(3),
                        rs.getString(4), rs.getInt(5));
                mList.add(med);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return mList;
    }
/*
    public ArrayList<HamSatinAl> buyList() {
        ArrayList<HamSatinAl> hList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey",
                    "root", "");
            String query = "SELECT tedarikci.firmaAdi, hammadde.isim, tedhammadde.stok,"
                    + " tedhammadde.fiyat FROM tedhammadde INNER JOIN hammadde"
                    + " ON tedhammadde.hammaddeID = hammadde.ID INNER JOIN tedarikci ON tedhammadde.uretenFirmaID = tedarikci.ID"
                    + " Order By hammadde.isim";

            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery(query);
            HamSatinAl ham;
            while (rs.next()) {
                ham = new HamSatinAl(rs.getString(1), rs.getString(2),
                        rs.getInt(3), rs.getInt(4));
                System.out.println(rs.getString(1) + " - - " + rs.getString(2) + "+ + " + rs.getInt(3) + "- - -" + rs.getInt(4));
                hList.add(ham);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return hList;
    }*/

    public ArrayList<ureticiStok> stokList() {
        ArrayList<ureticiStok> uList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey",
                    "root", "");
            String query = "SELECT `urunler`.`urunAd`, `urunler`.`stok` FROM `urunler`";

            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery(query);
            ureticiStok urun;
            while (rs.next()) {
                urun = new ureticiStok(rs.getString(1), rs.getInt(2));
                System.out.println(rs.getString(1) + " - - " + rs.getInt(2));
                uList.add(urun);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return uList;

    }

    public void showStokTable() {
        ArrayList<ureticiStok> usList = stokList();
        DefaultTableModel tableModel = (DefaultTableModel) uStokTable.getModel();

        Object[] row = new Object[2];
        for (int i = 0; i < usList.size(); i++) {
            row[0] = usList.get(i).getBilesik();
            row[1] = usList.get(i).getStok();
            tableModel.addRow(row);
        }
    }
/*
    public void showbuyTable() {
        ArrayList<HamSatinAl> hamList = buyList();
        DefaultTableModel tableModel = (DefaultTableModel) hamAlTable.getModel();

        Object[] row = new Object[4];
        for (int i = 0; i < hamList.size(); i++) {
            row[0] = hamList.get(i).getFirmaAdi();
            row[1] = hamList.get(i).getHamMadde();
            row[2] = hamList.get(i).getStok();
            row[3] = hamList.get(i).getFiyat();
            tableModel.addRow(row);
        }
    }*/

    public void showTed() {
        /*
        tedarikci.ID, tedarikci.firmaAdi, tedarikci.ulke, tedarikci.sehir, hammadde.isim, tedhammadde.stok, tedhammadde.uretimTarihi,"
                    + " tedhammadde.rafomru, tedhammadde.fiyat
         */
        ArrayList<Ted> tedList = tedList();
        DefaultTableModel tableModel = (DefaultTableModel) tedTable.getModel();

        Object[] row = new Object[9];
        //"ID  -CName  -Contry  -Product  -Quantity  -PDate  -ShelfLife  -SaleP"
        for (int i = 0; i < tedList.size(); i++) {
            row[0] = tedList.get(i).getId();
            row[1] = tedList.get(i).getFirmaAdi();
            row[2] = tedList.get(i).getUlke();
            row[3] = tedList.get(i).getSehir();
            row[4] = tedList.get(i).getMadde();
            row[5] = tedList.get(i).getMiktar();
            row[6] = tedList.get(i).getuTarihi();
            row[7] = tedList.get(i).getRaf();
            row[8] = tedList.get(i).getSatisFiyati();
            tableModel.addRow(row);
        }

    }

    public void showMusteri() {
        ArrayList<Musteri> mList = musteriList();
        DefaultTableModel tableModel = (DefaultTableModel) customerTable.getModel();

        Object[] row = new Object[5];
        for (int i = 0; i < mList.size(); i++) {
            row[0] = mList.get(i).getId();
            row[1] = mList.get(i).getMname();
            row[2] = mList.get(i).getMcity();
            row[3] = mList.get(i).getMproduct();
            row[4] = mList.get(i).getQuanitity();
            tableModel.addRow(row);
        }

    }

    public void showSiparis() {
        ArrayList<Musteri> mList = musteriList();
        DefaultTableModel tableModel = (DefaultTableModel) siparisTable.getModel();

        Object[] row = new Object[5];
        for (int i = 0; i < mList.size(); i++) {
            row[0] = mList.get(i).getId();
            row[1] = mList.get(i).getMname();
            row[2] = mList.get(i).getMcity();
            row[3] = mList.get(i).getMproduct();
            row[4] = mList.get(i).getQuanitity();
            tableModel.addRow(row);
        }
    }

    public void connectDatabase() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/dbprolab?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey", "root", "");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT tedarikci.ID, tedarikci.firmaAdi, tedarikci.ulke,"
                    + " tedarikci.sehir, hammadde.isim, tedhammadde.stok, tedhammadde.uretimTarihi,"
                    + " tedhammadde.rafomru, tedhammadde.fiyat FROM tedarikci, hammadde, tedhammadde WHERE tedhammadde.uretenFirmaID = tedarikci.ID AND hammadde.ID = tedhammadde.ID");
            System.out.println("ID  -CName  -Contry  -City  -Product  -Quantity  -PDate  -ShelfLife  -SaleP");
            while (rs.next()) {
                System.out.println(rs.getInt(1) + " | " + rs.getString(2) + " | " + rs.getString(3) + " | "
                        + rs.getString(4) + " | " + rs.getString(5) + " | "
                        + rs.getInt(6) + " | " + rs.getString(7) + " | "
                        + rs.getInt(8) + " | " + rs.getInt(9));
            }
            stmt.close();
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adresGuncButton;
    private javax.swing.JComboBox<String> citypane;
    private javax.swing.JTextPane countrypane;
    private javax.swing.JTable customerTable;
    private javax.swing.JTextPane datepane;
    private javax.swing.JTextPane fnamepane;
    private javax.swing.JTextPane idpane;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane karPane;
    private javax.swing.JTextPane karPane2;
    private javax.swing.JTextPane lifepane;
    private javax.swing.JTextPane mAdressPane;
    private javax.swing.JButton mEkleBtn;
    private javax.swing.JTextPane mIdPane;
    private javax.swing.JTextPane mNamePane;
    private javax.swing.JPanel mPanel;
    private javax.swing.JTextPane mProductPane;
    private javax.swing.JTextPane mQuanPane;
    private javax.swing.JTextField olusturBilesen;
    private javax.swing.JButton olusturButton;
    private javax.swing.JTextPane olusturMiktar;
    private javax.swing.JTextPane pricepane;
    private javax.swing.JTextPane productpane;
    private javax.swing.JTextPane quantitypane;
    private javax.swing.JPanel sPanel;
    private javax.swing.JTable siparisTable;
    private javax.swing.JPanel tPanel;
    private javax.swing.JButton tedEkleButton;
    private javax.swing.JTable tedTable;
    private javax.swing.JPanel uPanel;
    private javax.swing.JTable uStokTable;
    private javax.swing.JTextPane yolMaliyeti;
    // End of variables declaration//GEN-END:variables

}

class ureticiStok {

    private String bilesik;
    private int stok;

    public ureticiStok(String bilesik, int stok) {
        this.bilesik = bilesik;
        this.stok = stok;
    }

    public String getBilesik() {
        return bilesik;
    }

    public int getStok() {
        return stok;
    }

}
/*
class HamSatinAl {

    private String firmaAdi, hamMadde;
    private int stok, fiyat;

    public HamSatinAl(String firmaAdi, String hamMadde, int stok, int fiyat) {
        this.firmaAdi = firmaAdi;
        this.hamMadde = hamMadde;
        this.stok = stok;
        this.fiyat = fiyat;
    }

    public String getFirmaAdi() {
        return firmaAdi;
    }

    public String getHamMadde() {
        return hamMadde;
    }

    public int getStok() {
        return stok;
    }

    public int getFiyat() {
        return fiyat;
    }

}*/

class Musteri {

    private int id, quanitity;
    private String mname, mcity, mproduct;

    public Musteri(int id, String mname, String mcity, String mproduct, int quanitity) {
        this.id = id;
        this.quanitity = quanitity;
        this.mname = mname;
        this.mcity = mcity;
        this.mproduct = mproduct;
    }

    public int getId() {
        return id;
    }

    public int getQuanitity() {
        return quanitity;
    }

    public String getMname() {
        return mname;
    }

    public String getMcity() {
        return mcity;
    }

    public String getMproduct() {
        return mproduct;
    }

}

class Ted {

    private int id, miktar, raf, satisFiyati;
    private String firmaAdi, ulke, sehir, uTarihi, madde;

    //"ID  -CName  -Contry  -Product  -Quantity  -PDate  -ShelfLife  -SaleP"
    public Ted(int id, String firmaAdi, String ulke, String sehir, String madde,
            int miktar, String uTarihi, int raf, int satisFiyati) {
        this.id = id;
        this.miktar = miktar;
        this.raf = raf;
        this.satisFiyati = satisFiyati;
        this.firmaAdi = firmaAdi;
        this.ulke = ulke;
        this.sehir = sehir;
        this.uTarihi = uTarihi;
        this.madde = madde;
    }

    public String getMadde() {
        return madde;
    }

    public int getId() {
        return id;
    }

    public int getMiktar() {
        return miktar;
    }

    public int getRaf() {
        return raf;
    }

    public int getSatisFiyati() {
        return satisFiyati;
    }

    public String getFirmaAdi() {
        return firmaAdi;
    }

    public String getUlke() {
        return ulke;
    }

    public String getSehir() {
        return sehir;
    }

    public String getuTarihi() {
        return uTarihi;
    }
}
